#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "yunorunner"
name = "YunoRunner"
description.en = "A fully self-hosted CI runner of YunoHost"
description.fr = "Runner d'intégration continue de YunoHost"

version = "2024.12.10~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-or-later"
code = "https://github.com/YunoHost/yunorunner"

[integration]
yunohost = ">= 11.2"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.context]
    ask.en = "Leave it to 'personal-ci'. If set to 'official-infra', Yunorunner will take over your server and disable vital services to run alone."
    type = "select"
    choices.personal_ci = "Personal CI"
    choices.official_infra = "Official infra"
    default = "personal_ci"

    [install.mode]
    ask.en = "Self-hosted package only works in manual mode, but you may test as you see fit."
    type = "select"
    choices.auto = "Automatically from the catalog"
    choices.manual = "Manually via ciclic or webhook"
    default = "manual"

    [install.appsrepo]
    ask.en = "Your GitHub URL to apps.toml file (https://example.tld/user/apps)"
    type = "string"
    default = "https://github.com/YunoHost/apps"

    [install.executor]
    ask.en = "Insert the username of the user who will be eligible to trigger jobs in GitHub"
    type = "string"
    default = ""
    optional = false

    [install.publicdir]
    ask.en = "(OPTIONAL) If installing on a local domain, but exposing through a different one, insert the public domain here (https://sub.domain.tld)"
    type = "string"
    default = ""
    optional = true

    [install.githubtoken]
    ask.en = "Insert GitHub personal access token here"
    type = "string"
    optional = false

    [install.webhooksecret]
    ask.en = "Insert Webhook Secret token here"
    type = "string"
    optional = false

    [install.distributionchoice]
    ask.en = "Insert OS distribution of choice here (bullseye, bookworm, etc.)"
    type = "string"
    default = "bullseye"
    optional = false

    [install.ynhbranch]
    ask.en = "Insert YNH branch of choice (stable, testing, etc.)"
    type = "string"
    default = "stable"
    optional = false

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = [
        "python3-venv",
        "python3-dev",
        "python3-pip",
        "sqlite3",
        "wkhtmltopdf",
        "optipng",
        "lynx",

        # package checker deps
        "python3-six",
        "python3-jsonschema",
        "python3-pyparsing",
        "python3-toml",
    ]
