#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.context = "personal_ci"
    args.mode = "manual"
    args.cluster = false
    args.appsrepo = "https://github.com/YunoHost/apps"
    args.executor = "test"
    args.publicdir = "https://github.com/YunoHost/apps"
    args.githubtoken = "test"
    args.webhooksecret = "test"
    args.distributionchoice = "bullseye"
    args.ynhbranch = "stable"

    # ------------
    # Tests to run
    # ------------


