#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL INCUS
#=================================================
ynh_script_progression "Installing Incus... (this may take a long time!)"

if ! yunohost app list --output-as json --quiet | jq -e '.apps[] | select(.id == "incus")' >/dev/null; then
    yunohost app install --force https://github.com/YunoHost-Apps/incus_ynh
fi

setup_incus

#=================================================
# DOWNLOAD, CHECK, AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

_git_clone_or_pull "$install_dir/yunorunner"
_git_clone_or_pull "$install_dir/package_check" https://github.com/YunoHost/package_check

chown "$app:$app" "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R "$app:$app" "$install_dir"
chown "$app:www-data" "$install_dir" "$install_dir/yunorunner"
chown -R "$app:www-data" "$install_dir/yunorunner/results"

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing Python dependencies..."

pushd "$install_dir"
    python3 -m venv venv
    venv/bin/pip install --upgrade pip
    venv/bin/pip install -r package_check/requirements.txt
    venv/bin/pip install -r yunorunner/requirements.txt
    # package_check dep not in apt
    venv/bin/pip install imgkit
    venv/bin/pip install jsonschema
    venv/bin/pip install pyparsing
    venv/bin/pip install toml
popd

#=================================================
# CREATE AND CONFIGURE CONFIG.PY
#=================================================
ynh_script_progression "Configuring YunoRunner settings..."

# Check if $publicdir is set
if [ -z "$publicdir" ]; then
    # If not set, assign the default value
    publicdir="https://$domain"
    echo "No publicdir provided, setting default to https://$publicdir"
    ynh_app_setting_set --key="DIFFERENT" --value="false"
else
    # If set, use the provided value
    echo "Using provided publicdir: $publicdir"
    ynh_app_setting_set --key="DIFFERENT" --value="true"
fi

cat <<EOF > "$install_dir/yunorunner/config.py"
BASE_URL = "https://$domain"
BASE_PUBLIC_URL = "$publicdir"
EXECUTOR = "$executor"
APPSREPO = "$appsrepo"
PORT = $port
MONITOR_APPS_LIST = False
MONITOR_GIT = False
MONITOR_ONLY_GOOD_QUALITY_APPS = False
MONTHLY_JOBS = False
WORKER_COUNT = 1
YNH_BRANCH = "$ynhbranch"
DIST = "$distributionchoice"
PACKAGE_CHECK_DIR = "/var/www/yunorunner/package_check/"
GITHUB_COMMIT_STATUS_TOKEN = "$githubtoken"
GITHUB_WEBHOOK_SECRET = "$webhooksecret"
EOF

chmod 400 "$install_dir/yunorunner/config.py"
chown "$app:$app" "$install_dir/yunorunner/config.py"

ynh_app_setting_set --key="BASE_URL" --value="https://$domain"
ynh_app_setting_set --key="BASE_PUBLIC_URL" --value="$publicdir"
ynh_app_setting_set --key="EXECUTOR" --value="$executor"
ynh_app_setting_set --key="APPSREPO" --value="$appsrepo"
ynh_app_setting_set --key="PORT" --value="$port"
ynh_app_setting_set --key="YNH_BRANCH" --value="$ynhbranch"
ynh_app_setting_set --key="DIST" --value="$distributionchoice"
ynh_app_setting_set --key="GITHUB_COMMIT_STATUS_TOKEN" --value="$githubtoken"
ynh_app_setting_set --key="GITHUB_WEBHOOK_SECRET" --value="$webhooksecret"

#=================================================
# ADD SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx
ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

# Create a dedicated systemd config
yunohost service add "$app" --description="YunoRunner package testing service"
ynh_config_add_systemd

#=================================================
# APPLY PATCHES
#=================================================
ynh_script_progression "Applying patches to Python scripts..."

ynh_replace \
    --match=$'ci_name = app.config.BASE_URL.lower().replace(\"https://\", \"\").split(\".\")[0]' \
    --replace=$'ci_name = app.config.BASE_PUBLIC_URL.lower().replace(\"https://\", \"\").split(\".\")[0]' \
    --file="/var/www/yunorunner/yunorunner/run.py"

ynh_replace \
    --match="badge_url = app.config.BASE_URL + app.url_for(\"api_badge_job\", job_id=job.id)" \
    --replace="badge_url = app.config.BASE_PUBLIC_URL + app.url_for(\"api_badge_job\", job_id=job.id)" \
    --file="/var/www/yunorunner/yunorunner/run.py"

ynh_replace \
    --match="summary_url = app.config.BASE_URL + f\"/summary/{job.id}.png\"" \
    --replace="summary_url = app.config.BASE_PUBLIC_URL + f\"/summary/{job.id}.png\"" \
    --file="/var/www/yunorunner/yunorunner/run.py"

# Add new config variables to default_config
ynh_replace \
    --match="\"BASE_URL\": \"\"," \
    --replace="\"BASE_URL\": \"\",\n        \"BASE_PUBLIC_URL\": \"\",\n        \"EXECUTOR\": \"\",\n        \"APPSREPO\": \"\"," \
    --file="/var/www/yunorunner/yunorunner/run.py"

# Replace "github-actions[bot]" with app.config.EXECUTOR
ynh_replace \
    --match="\"github-actions\[bot\]\",\s*" \
    --replace="app.config.EXECUTOR," \
    --file="/var/www/yunorunner/yunorunner/run.py"

# Remove "yunohost-bot"
ynh_replace \
    --match="\"yunohost-bot\",\s*" \
    --replace="" \
    --file="/var/www/yunorunner/yunorunner/run.py"

# Replace "ci-auto-update-" with an empty string
ynh_replace \
    --match="\"ci-auto-update-"\" \
    --replace='""' \
    --file="/var/www/yunorunner/yunorunner/run.py"

# Replace the GitHub API membership check with an immediate return 204
ynh_replace \
    --match=$'f"https://api.github.com/orgs/YunoHost-Apps/members/{user}",' \
    --replace=$'f"https://api.github.com/orgs/YunoHost-Apps/members/tituspijean",' \
    --file="/var/www/yunorunner/yunorunner/run.py"

# Replace job_url in body statement with public_url
ynh_replace \
    --match='job_url = app.config.BASE_URL + app.url_for("html_job", job_id=job.id)' \
    --replace='job_url = app.config.BASE_URL + app.url_for("html_job", job_id=job.id)\n    public_url = app.config.BASE_PUBLIC_URL + app.url_for("html_job", job_id=job.id)' \
    --file="/var/www/yunorunner/yunorunner/run.py"

cat "$PWD/status-integration" >> "/var/www/yunorunner/yunorunner/run.py"

mv "$PWD/apply_changes.py" "/var/www/yunorunner/yunorunner/apply_changes.py"
chown "$app:$app" "/var/www/yunorunner/yunorunner/apply_changes.py"
chmod 744 "/var/www/yunorunner/yunorunner/apply_changes.py"
/usr/bin/env python3 "$PWD/run_job_changes.py"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --log_path="systemd"

#=================================================
# FINISH INSTALLATION
#=================================================
ynh_script_progression "Installation of $app completed!" --last
