#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL INCUS
#=================================================
ynh_script_progression "Installing Incus... (this may take a long time!)"

if ! yunohost app list --output-as json --quiet | jq -e '.apps[] | select(.id == "incus")' >/dev/null; then
    yunohost app install --force https://github.com/YunoHost-Apps/incus_ynh
fi

setup_incus

#=================================================
# DOWNLOAD, CHECK, AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

_git_clone_or_pull "$install_dir/yunorunner"
_git_clone_or_pull "$install_dir/package_check" https://github.com/YunoHost/package_check
_git_clone_or_pull "$install_dir/package_check/package_linter" https://github.com/YunoHost/package_linter

chown "$app:$app" "$install_dir"

chmod -R o-rwx "$install_dir"
chown -R "$app:$app" "$install_dir"
chown "$app:www-data" "$install_dir" "$install_dir/yunorunner"
chown -R "$app:www-data" "$install_dir/yunorunner/results"

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing Python dependencies..."

pushd "$install_dir"
    python3 -m venv venv
    venv/bin/pip install --upgrade pip
    venv/bin/pip install -r yunorunner/requirements.txt
    # package_check dep not in apt
    venv/bin/pip install imgkit
popd

#=================================================
# CREATE AND CONFIGURE CONFIG.PY
#=================================================
ynh_script_progression "Configuring YunoRunner settings..."

cat <<EOF > "$install_dir/yunorunner/config.py"
BASE_URL = "https://$domain"
BASE_PUBLIC_URL = "${publicdir:-}"
EXECUTOR = "${executor:-}"
APPSREPO = "$appsrepo"
PORT = 8095
MONITOR_APPS_LIST = False
MONITOR_GIT = False
MONITOR_ONLY_GOOD_QUALITY_APPS = False
MONTHLY_JOBS = False
WORKER_COUNT = 1
YNH_BRANCH = "$ynhbranch"
DIST = "$distributionchoice"
PACKAGE_CHECK_DIR = "/var/www/yunorunner/package_check/"
GITHUB_COMMIT_STATUS_TOKEN = "$githubtoken"
GITHUB_WEBHOOK_SECRET = "$webhooksecret"
EOF

chmod 400 "$install_dir/yunorunner/config.py"
chown "$app:$app" "$install_dir/yunorunner/config.py"

#=================================================
# ADD SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app" --description="$app daemon for YunoRunner"

#=================================================
# APPLY PATCHES
#=================================================
ynh_script_progression "Applying patches to Python scripts..."

# Replace BASE_URL with BASE_PUBLIC_URL
ynh_replace \
    --match="ci_name = app.config.BASE_URL.lower().replace(\"https://\", \"\").split(\".\")[0]" \
    --replace="ci_name = app.config.BASE_PUBLIC_URL.lower().replace(\"https://\", \"\").split(\".\")[0]" \
    --file="/var/www/yunorunner/yunorunner/run.py"

ynh_replace \
    --match="badge_url = app.config.BASE_URL + app.url_for(\"api_badge_job\", job_id=job.id)" \
    --replace="badge_url = app.config.BASE_PUBLIC_URL + app.url_for(\"api_badge_job\", job_id=job.id)" \
    --file="/var/www/yunorunner/yunorunner/run.py"

ynh_replace \
    --match="summary_url = app.config.BASE_URL + f\"/summary/{job.id}.png\"" \
    --replace="summary_url = app.config.BASE_PUBLIC_URL + f\"/summary/{job.id}.png\"" \
    --file="/var/www/yunorunner/yunorunner/run.py"

# Add new config variables to default_config
ynh_replace \
    --match="\"BASE_URL\": \"\"," \
    --replace="\"BASE_URL\": \"\",\n        \"BASE_PUBLIC_URL\": \"\",\n        \"EXECUTOR\": \"\",\n        \"APPSREPO\": \"\"," \
    --file="/var/www/yunorunner/yunorunner/run.py"

# Replace hardcoded repo URL
ynh_replace \
    --match="\"https://github.com/YunoHost/apps\"" \
    --replace="app.config.APPSREPO" \
    --file="/var/www/yunorunner/package_check/package_linter/tests/test_catalog.py"

# Replace YunoHost-Apps with app.config.EXECUTOR
ynh_replace \
    --match="\"https://github.com/YunoHost-Apps/%s_ynh\"" \
    --replace="f\"https://github.com/{app.config.EXECUTOR}/%s_ynh\"" \
    --file="/var/www/yunorunner/package_check/package_linter/tests/test_catalog.py"
# Replace "github-actions[bot]" with app.config.EXECUTOR
ynh_replace \
    --match="\"github-actions\[bot\]\",\s*" \
    --replace="app.config.EXECUTOR" \
    --file="/var/www/yunorunner/yunorunner/run.py"

# Remove "yunohost-bot"
ynh_replace \
    --match="\"yunohost-bot\",\s*" \
    --replace="" \
    --file="/var/www/yunorunner/yunorunner/run.py"

# Replace "ci-auto-update-" with an empty string
ynh_replace \
    --match="\"ci-auto-update-"\" \
    --replace='""' \
    --file="/var/www/yunorunner/yunorunner/run.py"

# Replace the GitHub API membership check with an immediate return 204
ynh_replace \
    --match=$'f"https://api.github.com/orgs/YunoHost-Apps/members/{user}",' \
    --replace='return resp.status == 204,' \
    --file="/var/www/yunorunner/yunorunner/run.py"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --log_path="systemd" --timeout=30

#=================================================
# FINISH INSTALLATION
#=================================================
ynh_script_progression "Installation of $app completed!" --last
